version: '3.3'

services:
  yarn_install:
    image: circleci/node:12.16.3
    command: bash -c "sudo yarn"
    volumes:
      - node-modules:/code/node_modules
      - .:/code
    working_dir: /code
    user: root
    stdin_open: true

  gatsby:
    image: circleci/node:12.16.3
    command: bash -c "sudo yarn develop -H 0.0.0.0"
    ports:
      - '8000:8000'
    volumes:
      - node-modules:/code/node_modules
      - .:/code
    working_dir: /code
    user: root
    stdin_open: true
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/

volumes:
  node-modules: {}
